config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  #posts
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    #image
    mount_uploader :image, ImageUploader
    
    validates_presence_of :title,:content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    def index
        @posts = Post.all
    end
    def new
        @post = Post.new
    end
    def create
        @post = Post.new post_params
        if @post.save
            redirect_to posts_path
        else
            render 'new'
        end
    end
    def show
    end
    def edit
    end
    def update
        
        if @post.update post_params
            redirect_to posts_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @post.destroy
        
        redirect_to posts_path
    end
    
    private
    def post_params
        params.require(:post).permit(:title, :content, :image)
    end
    def set_post
        @post = Post.find params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/_navbar.html.erb
<nav class="nav has-shadow">
  <div class="container">
    <div class="nav-left">

      <!-- todo: 加上連結 -->
      <%= link_to root_path class:'nav-item' do %>
        <%= image_tag 'Logo', alt: 'PlayForm Logo' %>
      <% end %>

    </div>
    <span class="nav-toggle">
      <span></span>
      <span></span>
      <span></span>
    </span>
    <div class="nav-right nav-menu">

      <!--  todo: 加上連結 -->
      <%= link_to '文章列表', posts_path, class:'nav-item is-tab'%>
      <%= link_to '新增文章', new_post_path, class:'nav-item is-tab'%>
      
      <% if current_user %>
        <%= link_to '帳戶管理', edit_user_registration_path, class:'nav-item is-tab'%>
        <%= link_to '登出', destroy_user_session_path, method: :delete, class:'nav-item'%>
      <% else %>
        <%= link_to '登入', new_user_session_path, class:'nav-item'%>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayForm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>

    <%= yield %>

  </body>
</html>

app/views/pages/homepage.html.erb
<section class="section">
  <div class="container has-text-centered">
    <h1 class="title is-4">Welcome to PlayForm!</h1>
  </div>
</section>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <div class="columns">
      <div class="column is-7">
        <div class="field">
          <%= f.label :image, '圖片', class:'label' %>
          <%= f.file_field :image %>
        </div>
      </div>
      <div class="column is-5">
        <div class="field">
          <%= f.label :title, '標題', class:'label' %>
          <div class="control">
            <%= f.text_field :title, class: 'input' %>
            <% @post.errors.full_messages_for(:title).each do |msg| %>
                <p class="is-danger help"><%= msg %></p>
            <% end %>
          </div>
        </div>
        <div class="field">
          <%= f.label :content, '內容', class:'label' %>
          <div class="control">
            <%= f.text_area :content, class: 'textarea' %>
            <% @post.errors.full_messages_for(:content).each do |msg| %>
                <p class="is-danger help"><%= msg %></p>
            <% end %>
          </div>
        </div>
        <div class="field">
          <%= f.submit 'submit', class: 'button is-primary is-medium is-fullwidth' %>
        </div>
      </div>
    </div>
<% end %>

app/views/posts/edit.html.erb
<section class="section store-form-section">
  <div class="container">
    <h1 class="title is-4">編輯文章</h1>
    <div class="box">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <section class="section post-section">
      <div class="container">
        <div class="card has-post">
          <div class="post-info">
            <%= link_to post_path(post) do %>
              <figure class="image is-3by2">
                <%= image_tag post.image %>
              </figure>
            <% end %>
            <div class="card-content has-border-right">
              <%= link_to edit_post_path(post), class:"button is-small is-primary is-outlined is-edit" do %>
                <i class="fa fa-pencil-square-o"></i>
              <% end %>
              <div class="media">
                <div class="media-content">
                  <%= link_to post_path(post) do %>
                    <p class="title is-4"><%= post.title %></p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        
        <div class="post-content">
            <div class="titlebar has-text-centered">content</div>
            <div class="card-content">
              <div class="column-is-multipleline">
                <div class="content has-content">
                  <%= truncate post.content, length:150 %>
                </div>
              </div>
              
            </div>
        </div>
      </div>
          
        </div>
        
    </section>
<% end %>

app/views/posts/new.html.erb
<section class="section store-form-section">
  <div class="container">
    <h1 class="title is-4">新增文章</h1>
    <div class="box">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="section contain-image-section">
  <div class="container">
    <figure class="image">
      <%= image_tag @post.image %>
        <div class="card">
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @post.title %></p>
              </div>
            </div>
            <div class="content has-content">
              <%= @post.content %>
            </div>
          </div>
          <div class="card-footer">
            <div class="card-footer-item">
              <%= link_to 'edit', edit_post_path(@post) %>
            </div>
            <div class="card-footer-item">
              <%= link_to 'delete', post_path(@post), method: :delete, data: {confirm: '確定要刪除嗎？'} %>
            </div>
          </div>
        </div>
    </figure>
  </div>
</section>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'button is-link' %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'button is-link' %>
<% end -%>